AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ALBSecurityGroup:
    Type: String
    
  Prefix:
    Type: String
    
  PublicSubnet1:
    Type: String
    
  PublicSubnet2:
    Type: String
    
  VPC:
    Type: String
    
Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${Prefix}-ALB    #  If you specify a name, you cannot perform updates that require replacement of this resource.
      Type: application
      IpAddressType: 'dualstack'  #'ipv4'
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: 'idle_timeout.timeout_seconds'
        Value: 60
      - Key: 'routing.http2.enabled'
        Value: 'true'      
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2

  HTTPListener1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions: 
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward

  # HTTPListener2:
  #   Type: "AWS::ElasticLoadBalancingV2::Listener"
  #   Properties:
  #       LoadBalancerArn: !Ref ApplicationLoadBalancer
  #       Port: 80
  #       Protocol: "HTTP"
  #       DefaultActions: 
  #         -  Type: redirect
  #            RedirectConfig:       #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-redirectconfig.html
  #               Protocol: "HTTPS"
  #               Port: "443"
  #               Host: "#{host}"
  #               Path: "/#{path}"
  #               Query: "#{query}"
  #               StatusCode: "HTTP_301"

  # HTTPSListener:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #       LoadBalancerArn: !Ref ALB
  #       Port: 443
  #       Protocol: "HTTPS"
  #       SslPolicy: "LBSecurityPolicy-TLS13-1-2-2021-06 "  # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
  #       Certificates: 
  #         - CertificateArn: arn:aws:acm:eu-central-1:**************:certificate/*********************
  #       DefaultActions: 
  #         - TargetGroupArn: !Ref ALBTargetGroup
  #           Type: forward


  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Name: !Sub ${Prefix}-ALBTargetGroup
      Protocol: HTTP
      Port: 8080
      TargetType: ip
      Matcher: 
        HttpCode: '200-499'
      HealthCheckProtocol: HTTP
      HealthCheckPath: /hostcheck
      #HealthCheckPort: traffic-port     # default 'traffic-port' which is the port on which each target receives traffic from the load balancer.
      HealthCheckIntervalSeconds: 30     # The approximate amount of time, in seconds, between health checks of an individual target.
      HealthCheckTimeoutSeconds: 10      # The amount of time, in seconds, during which no response from a target means a failed health check. 
      HealthyThresholdCount: 2           # The number of consecutive health check successes required before considering a target healthy.
      UnhealthyThresholdCount: 2         # The number of consecutive health check failures required before considering a target unhealthy.
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: "150"
      # etc

Outputs:
  ALBTargetGroup:
    Value: !Ref ALBTargetGroup

  URL:
    Value: !Sub 'http://${ALB.DNSName}'